import 'package:get/get.dart';

class LocaleString extends Translations {
  static String nameName = "You first" ;
  static String noOrderFee = "We don’t charge you order fees. We don’t spy on you. We just help you enjoy your meals" ;



  @override
  Map<String, Map<String, String>> get keys => {
    //ENGLISH LANGUAGE
    'en_US': {
      nameName: 'You first',
      noOrderFee: 'We don’t charge you order fees. We don’t spy on you. We just help you enjoy your meals',
      'Beautifully-designed menus' : 'Beautifully-designed menus',
      'Every menu item is manually reviewed by our team' : 'Every menu item is manually reviewed by our team',
      "Unbeatable rates":"Unbeatable rates",
      'We don’t charge any order fees. Delivery fees go where they belong.':'We don’t charge any order fees. Delivery fees go where they belong.',
      'WELCOME':'WELCOME',
      'Login your account.':'Login your account.',
      "Login With Mobile Number":"Login With Mobile Number",
      "Login With Email Address":"Login With Email Address",
      'Enter Mobile Number': 'Enter Mobile Number',
      'Please enter phone number': 'Please enter phone number',
      'Phone Number not register yet Please Signup' : 'Phone Number not register yet Please Signup',
      "OTP has been sent": "OTP has been sent",
      "Oops, OTP send failed": "Oops, OTP send failed",
      'Email not register yet Please Signup': 'Email not register yet Please Signup',
      'Enter your Mobile number':'Enter your Mobile number',
      'Please enter your phone number':'Please enter your phone number',
      'Please enter your email':'Please enter your email',
      'Enter a valid email address':'Enter a valid email address',
      'Please enter your otp':'Please enter your otp',
      'Enter Email' : 'Enter Email',
      'send': 'send',
      'Enter Otp':'Enter Otp',
      "OTP is verified": "OTP is verified",
      "Invalid OTP" : "Invalid OTP",
      'Login' : 'Login',
      'Customer Booking?' : 'Customer Booking?',
      'Sign in as a business': 'Sign in as a business',
      'Or Login with' : 'Or Login with',
      'Facebook': 'Facebook',
      'Google': 'Google',
      "Don't Have an Account?": "Don't Have an Account?",
      'Signup' : 'Signup',
      'Email already exits':'Email already exits',
      'Mobile Number already exits': 'Mobile Number already exits',
      "Create Account": "Create Account",
      "Enter Your Name": "Enter Your Name",
      "Please enter your name": "Please enter your name",
      'Enter your Email':'Enter your Email',
      "Valid Email is required":"Valid Email is required",
      "Email is required":"Email is required",
      "Please accept term and conditions":"Please accept term and conditions",
      "Email":"Email",
      "Mobile Number":"Mobile Number",
      'Phone Number':'Phone Number',
      'Signup as a customer':'Signup as a customer',
      'Restaurant Registration': 'Restaurant Registration',
      'Please enter your Restaurant Name':'Please enter your Restaurant Name',
      "Category": "Category",
      "Select category" : "Select category",
      'Please select category' : 'Please select category',
      "No Category Available": "No Category Available",
      "Address":"Address",
      "Location":"Location",
      'Accepted file types: JPEG, Doc, PDF, PNG':'Accepted file types: JPEG, Doc, PDF, PNG',
      'Yes I understand and agree to the ':'Yes I understand and agree to the ',
      'Terms And Conditions':'Terms And Conditions',
      'Terms and conditions are part of a contract that ensure parties understand their contractual rights and obligations. Parties draft them into a legal contract, also called a legal agreement, in accordance with local, state, and federal contract laws. They set important boundaries that all contract principals must uphold.''Several contract types utilize terms and conditions. When there is a formal agreement to create with another individual or entity, consider how you would like to structure your deal and negotiate the terms and conditions with the other side before finalizing anything. This strategy will help foster a sense of importance and inclusion on all sides.':'Terms and conditions are part of a contract that ensure parties understand their contractual rights and obligations. Parties draft them into a legal contract, also called a legal agreement, in accordance with local, state, and federal contract laws. They set important boundaries that all contract principals must uphold.''Several contract types utilize terms and conditions. When there is a formal agreement to create with another individual or entity, consider how you would like to structure your deal and negotiate the terms and conditions with the other side before finalizing anything. This strategy will help foster a sense of importance and inclusion on all sides.',
      'Save':'Save',
      'THANK YOU':'THANK YOU',
      'your account has been successfully created':'your account has been successfully created',
      "CONTINUE":"CONTINUE",
      'Dashboard':'Dashboard',
      'Menu':'Menu',
      'Promo Code List':'Promo Code List',
      'Slot List':'Slot List',
      'Total Earning':'Total Earning',
      'Set Store Time':'Set Store Time',
      'Bank Details':'Bank Details',
      'Setting':'Setting',
      'FeedBack':'FeedBack',
      'Log Out':'Log Out',
      'Hi':'Hi',
      "Restaurant Time:":"Restaurant Time:",
      "Gross Sales":"Gross Sales",
      "Earning":"Earning",
      "Sold items":"Sold items",
      "Order Received":"Order Received",
      "Latest Sales":"Latest Sales",
      "See All":"See All",
      "Order No.":"Order No.",
      "Status":"Status",
      "Menu List":"Menu List",
      'Find for food...':'Find for food...',
      "Delete Menu": "Delete Menu",
      "Are you sure you want to delete this Menu":"Are you sure you want to delete this Menu",
      "Cancel":"Cancel",
      "okay":"okay",
      "No Menu Created":"No Menu Created",
      "Add Menu":"Add Menu",
      "Dish Name":"Dish Name",
      'Please enter your menu name ':'Please enter your menu name ',
      'Meat Pasta':'Meat Pasta',
      "Price":"Price",
      'Please enter price':'Please enter price',
      "Discount":"Discount",
      "Menu Description":"Menu Description",
      'Please enter menu description ':'Please enter menu description ',
      "Upload images":"Upload images",
      'Delivery':'Delivery',
      'Dining':'Dining',
      'Please select image':'Please select image',
      'Please select booking type':'Please select booking type',
      'Select Picture from':'Select Picture from',
      'Cropper':'Cropper',
      "Camera":"Camera",
      'Gallery':'Gallery',
      'Orders':'Orders',
      'Wallet':'Wallet',
      'Order List':'Order List',
      "Your earning this month":"Your earning this month",
      "Withdrawal":"Withdrawal",
      "Filter":"Filter",
      "Yes":"Yes",
      "No":"No",
      "False":"False",
      "True":"True",
      "Search":"Search",
      "Dining Orders":"Dining Orders",
      "Delivery Orders":"Delivery Orders",
      "No User Found":"No User Found",
      "Withdrawal Money":"Withdrawal Money",
      "My Balance":"My Balance",
      "Amount":"Amount",
      "Date":"Date",
      "About Us":"About Us",
      'Please enter about yourself':'Please enter about yourself',
      "Upload Restaurant Images or Videos":"Upload Restaurant Images or Videos",
      "Upload Restaurant Menu Card":"Upload Restaurant Menu Card",
      'Image Gallery':'Image Gallery',
      'Choose From Gallery':'Choose From Gallery',
      "No Coupon Found":"No Coupon Found",
      "Create promo code":"Create promo code",
      "Update promo code":"Update promo code",
      'Code is Updated':'Code is Updated',
      'Code is Created':'Code is Created',
      "Promo Code Name":"Promo Code Name",
      'Please enter your Promo Code Name ':'Please enter your Promo Code Name ',
      'Sunday Code':'Sunday Code',
      'Code':'Code',
      'Happy sunday':'Happy sunday',
      'Please enter your Code ':'Please enter your Code ',
      'Please enter your Discount ':'Please enter your Discount ',
      "Max Discount":"Max Discount",
      "Start Date":"Start Date",
      'Please enter start Date ':'Please enter start Date ',
      'Select Start Date':'Select Start Date',
      "End Date":"End Date",
      'Please enter end Date ':'Please enter end Date ',
      'Select End Date':'Select End Date',
      'UPDATE COUPON':'UPDATE COUPON',
      'CREATE COUPON':'CREATE COUPON',
      'basad on 23 reviews':'basad on 23 reviews',
      'Excellent        ':'Excellent        ',
      'Good               ':'Good               ',
      'Average          ':'Average          ',
      'Below Average':'Below Average',
      "Set Delivery":"Set Delivery",
      "Cancellation":"Cancellation",
      "Menu selection":"Menu selection",
      "Preparation time":"Preparation time",
      'Please enter your preparation Time':'Please enter your preparation Time',
      'Mint':'Mint',
      "Average meal for 1 Member":"Average meal for 1 Member",
      'Please enter your average Meal For 1 Member':'Please enter your average Meal For 1 Member',
      'Submit':'Submit',
      "Please enter bank account Name":"Please enter bank account Name",
      "Bank Account Number":"Bank Account Number",
      "Please enter bank account number":"Please enter bank account number",
      "Account Holder Name":"Account Holder Name",
      "Please enter account holder name":"Please enter account holder name",
      "IFSC Code":"IFSC Code",
      "Please enter IFSC code":"Please enter IFSC code",
      "ADD ACCOUNT":"ADD ACCOUNT",
      "Withdrawal Amount":"Withdrawal Amount",
      "Order ID:":"Order ID:",
      "Admin Commission":"Admin Commission",
      "Slots are not created yet":"Slots are not created yet",
      "Create Slot":"Create Slot",
      "Single Date":"Single Date",
      "Date Range":"Date Range",
      "Start date is required":"Start date is required",
      "End date is required":"End date is required",
      "Lunch Time Slot":"Lunch Time Slot",
      "Previous Slots":"Previous Slots",
      "Create New":"Create New",
      "Dinner Time Slot":"Dinner Time Slot",



    },

    //Spanish LANGUAGE
    'es-ES': {

      'You first' :'tú primero',
      'We don’t charge you order fees. We don’t spy on you. We just help you enjoy your meals': 'No le cobramos tarifas de pedido. No te espiamos. Solo te ayudamos a disfrutar de tus comidas.',
      'Beautifully-designed menus' : 'Menús bellamente diseñados',
      'Every menu item is manually reviewed by our team' : 'Nuestro equipo revisa manualmente cada elemento del menú.',
      "Unbeatable rates":  "Tarifas inmejorables",
      'We don’t charge any order fees. Delivery fees go where they belong.':  'No cobramos ninguna tarifa de pedido. Los gastos de envío van a donde pertenecen.',
      'WELCOME':'BIENVENIDO',
      'Login your account.':  'Inicie sesión en su cuenta.',
      "Login With Mobile Number":  "Iniciar sesión con número de móvil",
      "Login With Email Address":  "Iniciar sesión con dirección de correo electrónico",
      'Enter Mobile Number': 'Ingrese el número de móvil',
      'Please enter phone number': 'Por favor ingrese el número de teléfono',
      'Phone Number not register yet Please Signup' : 'Número de teléfono aún no registrado Por favor regístrese',
      "OTP has been sent": "OTP ha sido enviado",
      "Oops, OTP send failed": "Vaya, falló el envío de OTP",
      'Email not register yet Please Signup': 'Correo electrónico aún no registrado Por favor regístrese',
      'Enter your Mobile number':  'Ingrese su numero celular',
      'Please enter your phone number': 'Por favor, introduzca su número de teléfono',
      'Please enter your email':  'Por favor introduzca su correo electrónico',
      'Enter a valid email address':  'Introduzca una dirección de correo electrónico válida',
      'Please enter your otp':  'Por favor ingresa tu OTP',
      'Enter Email' : 'Ingrese correo electrónico',
      'send': 'enviar',
      'Enter Otp': 'Ingrese a OTP',
      "OTP is verified": "OTP está verificado",
      "Invalid OTP" : "OTP no válida",
      'Login' : 'Acceso',
      'Customer Booking?' : '¿Reserva del cliente?',
      'Sign in as a business': 'Iniciar sesión como empresa',
      'Or Login with' : 'O inicia sesión con',
      'Facebook': 'Facebook',
      'Google': 'Google',
      "Don't Have an Account?": "¿No tienes una cuenta?",
      'Signup' : 'Inscribirse',
      'Email already exits': 'El correo electrónico ya existe',
      'Mobile Number already exits': 'El número de móvil ya existe',
      "Create Account": "Crear una cuenta",
      "Enter Your Name": "Introduzca su nombre",
      "Please enter your name": "por favor, escriba su nombre",
      'Enter your Email':  'Introduce tu correo electrónico',
      "Valid Email is required":  "Se requiere un correo electrónico válido",
      "Email is required": "correo electronico es requerido",
      "Please accept term and conditions": "Por favor acepte términos y condiciones",
      "Email": "Correo electrónico",
      "Mobile Number":  "Número de teléfono móvil",
      'Phone Number': 'Número de teléfono',
      'Signup as a customer':'Regístrate como cliente',
      'Restaurant Registration': 'Registro de restaurante',
      'Please enter your Restaurant Name':'Por favor introduce el nombre de tu restaurante',
      "Category": "Categoría",
      "Select category" : "Selecciona una categoría",
      'Please select category' : 'Por favor seleccione categoría',
      "No Category Available": "Ninguna categoría disponible",
      "Address": "DIRECCIÓN",
      "Location": "Ubicación",
      'Accepted file types: JPEG, Doc, PDF, PNG':'Tipos de archivos aceptados: JPEG, Doc, PDF, PNG',
      'Yes I understand and agree to the ':'Sí, entiendo y acepto las',
      'Terms And Conditions':  'Términos y condiciones',
      'Terms and conditions are part of a contract that ensure parties understand their contractual rights and obligations. Parties draft them into a legal contract, also called a legal agreement, in accordance with local, state, and federal contract laws. They set important boundaries that all contract principals must uphold.''Several contract types utilize terms and conditions. When there is a formal agreement to create with another individual or entity, consider how you would like to structure your deal and negotiate the terms and conditions with the other side before finalizing anything. This strategy will help foster a sense of importance and inclusion on all sides.'
          :'Los términos y condiciones son parte de un contrato que garantiza que las partes comprendan sus derechos y obligaciones contractuales. Las partes los redactan en un contrato legal, también llamado acuerdo legal, de acuerdo con las leyes contractuales locales, estatales y federales. Establecen límites importantes que todos los principios contractuales deben respetar. ''Varios tipos de contratos utilizan términos y condiciones. Cuando exista un acuerdo formal para crear con otro individuo o entidad, considere cómo le gustaría estructurar su trato y negocie los términos y condiciones con la otra parte antes de finalizar cualquier cosa. Esta estrategia ayudará a fomentar un sentido de importancia e inclusión en todas las partes.',
      'Save':  'Ahorrar',
      'THANK YOU':  'GRACIAS',
      'your account has been successfully created': 'Su cuenta ha sido creada satisfactoriamente',
      "CONTINUE": "CONTINUAR",
      'Dashboard':'salpicadero',
      'Menu':'Menú',
      'Promo Code List':'Lista de códigos promocionales',
      'Slot List':'Lista de Ranura',
      'Total Earning':'Ganador Total',
      'Set Store Time':'Establecer tiempo de tienda',
      'Bank Details':'Detalles del banco',
      'Setting':'Configuración',
      'FeedBack': 'Comentario',
      'Log Out':  'Cerrar sesión',
      'Hi':'Hola',
      "Restaurant Time:":"Hora del restaurante:",
      "Gross Sales":"Ventas brutas",
      "Earning":"Ganador",
      "Sold items":"Artículos vendidos",
      "Order Received":"orden recibida",
      "Latest Sales": "Últimas ventas",
      "See All":"Ver todo",
      "Order No.":"Número de orden",
      "Status":  "Estado",
      'Menu List':  'Lista de menú',
      'Find for food...':'Buscar comida...',
      "Delete Menu": "Eliminar menú",
      "Are you sure you want to delete this Menu":"¿Estás seguro de que deseas eliminar este menú?",
      "Cancel": "Cancelar",
      "okay":  "bueno",
      "No Menu Created":"No se creó ningún menú",
      "Add Menu":"Agregar menú",
      "Dish Name":"Nombre del plato",
      'Please enter your menu name ':'Por favor ingresa el nombre de tu menú',
      'Meat Pasta':'Pastas De Carne',
      "Price":"Precio",
      'Please enter price':'Por favor ingrese el precio',
      "Discount":"Descuento",
      "Menu Description":"Descripción del menú",
      'Please enter menu description ':'Por favor ingrese la descripción del menú',
      'Delivery':  'Entrega',
      "Upload images": "Subir imágenes",
      'Dining': 'Comida',
      'Please select image': 'Por favor seleccione imagen',
      'Please select booking type':  'Por favor seleccione el tipo de reserva',
      'Select Picture from': 'Seleccione Imagen de',
      'Cropper': 'Cultivador',
      "Camera": "Cámara",
      'Gallery':  'Galería',
      'Orders': 'Pedidos',
      'Wallet': 'Billetera',
      'Order List': 'Lista de orden',
      "Your earning this month":"Tus ganancias este mes",
      "Withdrawal":"Retiro",
      "Filter":"Filtrar",
      "Yes":"Sí",
      "No":"No",
      "False":"Falso",
      "True":"Verdadero",
      "Search":"Buscar",
      "Dining Orders":"Órdenes de cena",
      "Delivery Orders":  "Órdenes de entrega",
      "No User Found":"Usuario no encontrado",
      "Withdrawal Money":"Retiro de dinero",
      "My Balance":"Mi balance",
      "Amount":"Cantidad",
      "Date": "Fecha",
      "About Us":"Sobre nosotros",
      'Please enter about yourself': 'Por favor ingresa sobre ti',
      "Upload Restaurant Images or Videos":  "Subir imágenes o vídeos de restaurantes",
      "Upload Restaurant Menu Card": "Cargar tarjeta de menú de restaurante",
      'Image Gallery':  'galería de imágenes',
      'Choose From Gallery':  'Elegir de la galería',
      "No Coupon Found":  "No se encontró ningún cupón",
      "Create promo code": "Crear código promocional",
      "Update promo code":  "Actualizar código promocional",
      'Code is Updated': 'El código está actualizado',
      'Code is Created':  'Se crea el código',
      "Promo Code Name":  "Nombre del código promocional",
      'Please enter your Promo Code Name ':  'Por favor ingrese el nombre de su código promocional',
      'Sunday Code': 'Código dominical',
      'Code': 'Código',
      'Happy sunday': 'Feliz domingo',
      'Please enter your Code ': 'Por favor ingresa tu código',
      'Please enter your Discount ':  'Por favor ingrese su descuento',
      "Max Discount":  "Descuento máximo",
      "Start Date":  "Fecha de inicio",
      'Please enter start Date ':  'Por favor ingrese la fecha de inicio',
      'Select Start Date':  'Seleccione la fecha de inicio',
      "End Date":  "Fecha final",
      'Please enter end Date ':  'Por favor ingrese la fecha de finalización',
      'Select End Date':  'Seleccionar fecha de finalización',
      'UPDATE COUPON': 'ACTUALIZAR CUPÓN',
      'CREATE COUPON': 'CREAR CUPÓN',
      'basad on 23 reviews':  'Basado en 23 opiniones',
      'Excellent':'Excelente',
      'Good':'Bueno',
      'Average':'Promedio',
      'Below Average': 'Por debajo del promedio',
      "Chat/Email":  "Chat/correo electrónico",
      "Resvago team": "equipo resvago",
      "FAQ": "Preguntas más frecuentes",
      'here': 'aquí',
      "Set Delivery":  "Establecer entrega",
      "Cancellation":  "Cancelación",
      "Menu selection": "Selección de menú",
      "Preparation time": "Tiempo de preparación",
      'Please enter your preparation Time':  'Por favor ingrese su tiempo de preparación',
      'Mint': 'menta',
      "Average meal for 1 Member":  "Comida promedio para 1 Miembro",
      'Please enter your average Meal For 1 Member': 'Por favor ingrese su comida promedio para 1 miembro',
      'Submit': 'Entregar',
      "Please enter bank account Name":  "Por favor ingrese el nombre de la cuenta bancaria",
      "Bank Account Number": "Número de cuenta bancaria",
      "Please enter bank account number":  "Por favor ingrese el número de cuenta bancaria",
      "Account Holder Name": "nombre del titular de la cuenta",
      "Please enter account holder name":  "Por favor ingrese el nombre del titular de la cuenta",
      "IFSC Code": "Código IFSC",
      "Please enter IFSC code":  "Por favor ingrese el código IFSC",
      "ADD ACCOUNT":  "AÑADIR CUENTA",
      "Order ID:": "Solicitar ID:",
      "Withdrawal Amount":"Cantidad de retiro",
      "Admin Commission":"Comisión administrativa",
      "Slots are not created yet":"Los espacios aún no están creados",
      "Create Slot":"Crear ranura",
      "Single Date":"Fecha única",
      "Date Range":"Rango de fechas",
      "Start date is required":"Se requiere fecha de inicio",
      "End date is required":"Se requiere fecha de finalización",
      "Lunch Time Slot":"Horario del almuerzo",
      "Previous Slots":"Ranuras anteriores",
      "Create New":"Crear nuevo",
      "Dinner Time Slot":"Horario de la cena",




    },

    // french Language
    'fr_FR' : {

      'You first': 'Toi en premier',
      'We don’t charge you order fees. We don’t spy on you. We just help you enjoy your meals': 'Nous ne vous facturons pas de frais de commande. Nous ne vous espionnons pas. Nous vous aidons simplement à profiter de vos repas',
      'Beautifully-designed menus' : 'Des menus magnifiquement conçus',
      'Every menu item is manually reviewed by our team' : 'Chaque élément du menu est examiné manuellement par notre équipe',
      "Unbeatable rates": "Des tarifs imbattables",
      'We don’t charge any order fees. Delivery fees go where they belong.':'Nous ne facturons aucun frais de commande. Les frais de livraison vont là où ils appartiennent.',
      'WELCOME': 'BIENVENU',
      'Login your account.':'Connectez-vous à votre compte.',
      "Login With Mobile Number": "Connectez-vous avec un numéro de mobile",
      "Login With Email Address": "Connectez-vous avec une adresse e-mail",
      'Enter Mobile Number': 'Entrez le numéro de portable',
      'Please enter phone number': 'Veuillez entrer le numéro de téléphone',
      'Phone Number not register yet Please Signup' : 'Le numéro de téléphone n\'est pas encore enregistré Veuillez vous inscrire',
      "OTP has been sent": "OTP a été envoyé",
      "Oops, OTP send failed": "Oups, l'envoi OTP a échoué",
      'Email not register yet Please Signup': 'E-mail pas encore enregistré Veuillez vous inscrire',
      'Enter your Mobile number':'Entrez votre numéro de mobile',
      'Please enter your phone number':'Veuillez entrer votre numéro de téléphone',
      'Please enter your email':'Veuillez entrer votre email',
      'Enter a valid email address':'Entrez une adresse mail valide',
      'Please enter your otp':'Veuillez entrer votre OTP',
      'Enter Email' : 'Entrez votre e-mail',
      'send': 'envoyer',
      'Enter Otp':'Entrez OTP',
      "OTP is verified": "OTP est vérifié",
      "Invalid OTP" : "OTP invalide",
      'Login' : 'Se connecter',
      'Customer Booking?' : 'Réservation client ?',
      'Sign in as a business': 'Connectez-vous en tant qu\'entreprise',
      'Or Login with' : 'Ou connectez-vous avec',
      'Facebook': 'Facebook',
      'Google': 'Google',
      "Don't Have an Account?": "Vous n'avez pas de compte ?",
      'Signup' : 'S\'inscrire',
      'Email already exits':'L\'e-mail existe déjà',
      'Mobile Number already exits': 'Le numéro de mobile existe déjà',
      "Create Account": "Créer un compte",
      "Enter Your Name": "Entrez votre nom",
      "Please enter your name": "S'il vous plaît entrez votre nom",
      'Enter your Email':'Entrer votre Email',
      "Valid Email is required": "Un e-mail valide est requis",
      "Email is required":"L'e-mail est requis",
      "Please accept term and conditions":"Veuillez accepter les termes et conditions",
      "Email":"E-mail",
      "Mobile Number":"Numéro de portable",
      'Phone Number':'Numéro de téléphone',
      'Signup as a customer':'S\'inscrire en tant que client',
      'Restaurant Registration': 'Inscription au restaurant',
      'Please enter your Restaurant Name':'Veuillez entrer le nom de votre restaurant',
      "Category": "Catégorie",
      "Select category" : "Choisir une catégorie",
      'Please select category' : 'Veuillez sélectionner une catégorie',
      "No Category Available": "Aucune catégorie disponible",
      "Address":"Adresse",
      "Location":"Emplacement",
      'Accepted file types: JPEG, Doc, PDF, PNG': 'Types de fichiers acceptés : JPEG, Doc, PDF, PNG',
      'Yes I understand and agree to the ': 'Oui, je comprends et j\'accepte le',
      'Terms And Conditions':'Termes et conditionsSSSSS',
      'Terms and conditions are part of a contract that ensure parties understand their contractual rights and obligations. Parties draft them into a legal contract, also called a legal agreement, in accordance with local, state, and federal contract laws. They set important boundaries that all contract principals must uphold.''Several contract types utilize terms and conditions. When there is a formal agreement to create with another individual or entity, consider how you would like to structure your deal and negotiate the terms and conditions with the other side before finalizing anything. This strategy will help foster a sense of importance and inclusion on all sides.'
        :'Les termes et conditions font partie d\'un contrat qui garantit que les parties comprennent leurs droits et obligations contractuels. Les parties les rédigent dans un contrat juridique, également appelé accord juridique, conformément aux lois contractuelles locales, étatiques et fédérales. Ils fixent des limites importantes que tous les donneurs d\'ordre doivent respecter. » « Plusieurs types de contrats utilisent des termes et conditions. Lorsqu\'il existe un accord formel à conclure avec une autre personne ou entité, réfléchissez à la manière dont vous souhaitez structurer votre accord et négociez les termes et conditions avec l\'autre partie avant de finaliser quoi que ce soit. Cette stratégie contribuera à favoriser un sentiment d’importance et d’inclusion de toutes les parties.',
      'Save':'Sauvegarder',
      'THANK YOU': 'MERCI',
      'your account has been successfully created':'Votre compte à été créé avec succès',
      "CONTINUE":"CONTINUER",
      'Dashboard':'Tableau de bord',
      'Menu':'le menu',
      'Promo Code List':'Liste des codes promotionnels',
      'Slot List':'Liste des emplacements',
      'Total Earning':'Gain total',
      'Set Store Time':'Définir l\'heure du magasin',
      'Bank Details':'Coordonnées bancaires',
      'Setting':'Paramètre',
      'FeedBack':'Retour',
      'Log Out':'Se déconnecter',
      'Hi':'Salut',
      "Restaurant Time:":"Heure du restaurant :",
      "Gross Sales":"Ventes brutes",
      "Earning":"Revenus",
      "Sold items":"Articles vendus",
      "Order Received":"Ordre reçu",
      "Latest Sales":"Dernières ventes",
      "See All":"Voir tout",
      "Order No.":"Numéro de commande",
      "Status":"Statut",
      "Menu List":"Liste des menus",
      'Find for food...':'Trouver de la nourriture...',
      "Delete Menu": "Supprimer le menu",
      "Are you sure you want to delete this Menu":"Êtes-vous sûr de vouloir supprimer ce menu",
      "Cancel":"Annuler",
      "okay":"d'accord",
      "No Menu Created":"Aucun menu créé",
      "Add Menu":"Ajouter un menu",
      "Dish Name":"Nom du plat",
      'Please enter your menu name ':'Veuillez entrer le nom de votre menu',
      'Meat Pasta':'Pâtes à la viande',
      "Price":"Prix",
      'Please enter price':'Veuillez entrer le prix',
      "Discount":"Rabais",
      "Menu Description":"Description des menus",
      'Please enter menu description ':'Veuillez entrer la description du menu',
      "Upload images":"Importer des images",
      'Delivery':'Livraison',
      'Dining':'À manger',
      'Please select image':'Veuillez sélectionner une image',
      'Please select booking type':'Veuillez sélectionner le type de réservation',
      'Select Picture from':'Sélectionnez une image dans',
      'Cropper':'Recadrage',
      "Camera":"Caméra",
      'Gallery':'Galerie',
      'Orders':'ordres',
      'Wallet':'Portefeuille',
      'Order List':'Liste de commande',
      "Your earning this month":"Vos gains ce mois-ci",
      "Withdrawal":"Retrait",
      "Filter":"Filtre",
      "Yes":"Oui",
      "No":"Non",
      "False":"FAUX",
      "True":"Vrai",
      "Search":"Recherche",
      "Dining Orders":"Dining Orders",
      "Delivery Orders":"Bons de livraison",
      "No User Found": "Aucun utilisateur trouvé",
      "Withdrawal Money":"Retrait d'argent",
      "My Balance": "Mon solde",
      "Amount": "Montant",
      "Date": "Date",
      "About Us": "À propos de nous",
      'Please enter about yourself':'Veuillez entrer à propos de vous',
      "Upload Restaurant Images or Videos": "Télécharger des images ou des vidéos de restaurants",
      "Upload Restaurant Menu Card": "Télécharger la carte du menu du restaurant",
      'Image Gallery': 'Galerie d\'images',
      'Choose From Gallery': 'Choisir depuis la galerie',
      "No Coupon Found": "Aucun coupon trouvé",
      "Create promo code": "Créer un code promotionnel",
      "Update promo code": "Mettre à jour le code promotionnel",
      'Code is Updated':'Le code est mis à jour',
      'Code is Created':'Le code est créé',
      "Promo Code Name":"Nom du code promotionnel",
      'Please enter your Promo Code Name ':'Veuillez saisir le nom de votre code promotionnel',
      'Sunday Code':'Code du dimanche',
      'Code':'Code',
      'Happy sunday':'Bon dimanche',
      'Please enter your Code ':'Veuillez entrer votre code',
      'Please enter your Discount ':'Veuillez entrer votre réduction',
      "Max Discount":"Remise maximale",
      "Start Date":"Date de début",
      'Please enter start Date ':'Veuillez entrer la date de début',
      'Select Start Date':'Sélectionnez la date de début',
      "End Date":"Date de fin",
      'Please enter end Date ':'Veuillez entrer la date de fin',
      'Select End Date':'Sélectionnez la date de fin',
      'UPDATE COUPON':'COUPON DE MISE À JOUR',
      'CREATE COUPON':'CRÉER UN COUPON',
      'basad on 23 reviews':'basad sur 23 avis',
      'Excellent        ':'Excellent',
      'Good               ':'Bien',
      'Average          ':'Moyenne',
      'Below Average':'Sous la moyenne',
      "Set Delivery":"Définir la livraison",
      "Cancellation":"Annulation",
      "Menu selection":"Sélection des menus",
      "Preparation time":"Temps de préparation",
      'Please enter your preparation Time':'Veuillez entrer votre temps de préparation',
      'Mint':'minute',
      "Average meal for 1 Member":"Repas moyen pour 1 Membre",
      'Please enter your average Meal For 1 Member':'Veuillez entrer votre repas moyen pour 1 membre',
      'Submit':'Soumettre',
      "Please enter bank account Name":"Veuillez saisir le nom du compte bancaire",
      "Bank Account Number":"Numéro de compte bancaire",
      "Please enter bank account number":"Veuillez saisir le numéro de compte bancaire",
      "Account Holder Name":"Nom du titulaire du compte",
      "Please enter account holder name":"Veuillez saisir le nom du titulaire du compte",
      "IFSC Code":"Code IFSC",
      "Please enter IFSC code":"Veuillez entrer le code IFSC",
      "ADD ACCOUNT":"AJOUTER UN COMPTE",
      "Withdrawal Amount":"Montant de retrait",
      "Order ID:":"Numéro de commande:",
      "Admin Commission":"Commission d'administration",
      "Slots are not created yet":"Les emplacements ne sont pas encore créés",
      "Create Slot":"Créer un emplacement",
      "Single Date":"Rendez-vous unique",
      "Date Range":"Plage de dates",
      "Start date is required":"La date de début est requise",
      "End date is required":"La date de fin est obligatoire",
      "Lunch Time Slot":"Créneau horaire du déjeuner",
      "Previous Slots":"Machines à sous précédentes",
      "Create New":"Créer un nouveau",
      "Dinner Time Slot":"Créneau horaire du dîner",
    },

    // Arabic Language
    'ar_AE' : {
      'You first': 'أنت أولاً',
      'We don’t charge you order fees. We don’t spy on you. We just help you enjoy your meals': 'نحن لا نفرض عليك رسوم الطلب. نحن لا نتجسس عليك. نحن نساعدك فقط على الاستمتاع بوجباتك',
      'Beautifully-designed menus' : 'قوائم مصممة بشكل جميل',
      'Every menu item is manually reviewed by our team' : 'تتم مراجعة كل عنصر في القائمة يدويًا بواسطة فريقنا',
      "Unbeatable rates":"معدلات لا تقبل المنافسة",
      'We don’t charge any order fees. Delivery fees go where they belong.':'نحن لا نفرض أي رسوم على الطلب. رسوم التوصيل تذهب إلى حيث تنتمي.',
      'WELCOME':'مرحباً',
      'Login your account.':'قم بتسجيل الدخول إلى حسابك.',
      "Login With Mobile Number":"تسجيل الدخول برقم الجوال",
      "Login With Email Address":"تسجيل الدخول باستخدام عنوان البريد الإلكتروني",
      'Enter Mobile Number': 'أدخل رقم الجوال',
      'Please enter phone number': 'الرجاء إدخال رقم الهاتف',
      'Phone Number not register yet Please Signup' : 'رقم الهاتف لم يتم التسجيل بعد الرجاء الاشتراك',
      "OTP has been sent": "تم إرسال كلمة المرور لمرة واحدة",
      "Oops, OTP send failed": "عفوًا، فشل إرسال OTP",
      'Email not register yet Please Signup': 'البريد الإلكتروني لم يتم التسجيل بعد يرجى الاشتراك',
      'Enter your Mobile number':'أدخل رقم هاتفك المحمول',
      'Please enter your phone number':'يرجى إدخال رقم الهاتف الخاص بك',
      'Please enter your email':'رجاءا أدخل بريدك الإلكتروني',
      'Enter a valid email address':'أدخل عنوان بريد إلكتروني صالح',
      'Please enter your otp':'الرجاء إدخال كلمة المرور الخاصة بك',
      'Enter Email' : 'أدخل البريد الإلكتروني',
      'send': 'يرسل',
      'Enter Otp':'أدخل كلمة المرور',
      "OTP is verified": "تم التحقق من OTP",
      "Invalid OTP" : "كلمة المرور لمرة واحدة غير صالحة",
      'Login' : 'تسجيل الدخول',
      'Customer Booking?' : 'حجز العملاء؟',
      'Sign in as a business': 'تسجيل الدخول كعمل تجاري',
      'Or Login with' : 'أو تسجيل الدخول باستخدام',
      'Facebook': 'فيسبوك',
      'Google': 'جوجل',
      "Don't Have an Account?": "ليس لديك حساب؟",
      'Signup' : 'اشتراك',
      'Email already exits':'البريد الإلكتروني يخرج بالفعل',
      'Mobile Number already exits': 'رقم الجوال موجود بالفعل',
      "Create Account": "إنشاء حساب",
      "Enter Your Name": "أدخل أسمك",
      "Please enter your name": "من فضلك أدخل إسمك",
      'Enter your Email':'أدخل بريدك الإلكتروني',
      "Valid Email is required":"مطلوب بريد إلكتروني صالح",
      "Email is required":"البريد الالكتروني مطلوب",
      "Please accept term and conditions":"يرجى قبول الشروط والأحكام",
      "Email":"بريد إلكتروني",
      "Mobile Number":"رقم الهاتف المحمول",
      'Phone Number':'رقم التليفون',
      'Signup as a customer':'قم بالتسجيل كعميل',
      'Restaurant Registration': 'تسجيل المطعم',
      'Please enter your Restaurant Name':'الرجاء إدخال اسم المطعم الخاص بك',
      "Category": "فئة",
      "Select category" : "اختر الفئة",
      'Please select category' : 'الرجاء تحديد الفئة',
      "No Category Available": "لا توجد فئة متاحة",
      "Address":"عنوان",
      "Location":"Location",
      'Accepted file types: JPEG, Doc, PDF, PNG':'أنواع الملفات المقبولة: JPEG، Doc، PDF، PNG',
      'Yes I understand and agree to the ':'نعم أفهم وأوافق على',
      'Terms And Conditions':'الأحكام والشروط',
      'Terms and conditions are part of a contract that ensure parties understand their contractual rights and obligations. Parties draft them into a legal contract, also called a legal agreement, in accordance with local, state, and federal contract laws. They set important boundaries that all contract principals must uphold.''Several contract types utilize terms and conditions. When there is a formal agreement to create with another individual or entity, consider how you would like to structure your deal and negotiate the terms and conditions with the other side before finalizing anything. This strategy will help foster a sense of importance and inclusion on all sides.':
      'الشروط والأحكام هي جزء من العقد الذي يضمن فهم الأطراف لحقوقهم والتزاماتهم التعاقدية. تقوم الأطراف بصياغتها في عقد قانوني، يُسمى أيضًا اتفاقية قانونية، وفقًا لقوانين العقود المحلية والولائية والفدرالية. إنهم يضعون حدودًا مهمة يجب على جميع مديري العقود الالتزام بها.''تستخدم العديد من أنواع العقود الشروط والأحكام. عندما يكون هناك اتفاق رسمي للإنشاء مع فرد أو كيان آخر، فكر في الطريقة التي تريد بها هيكلة صفقتك والتفاوض على الشروط والأحكام مع الجانب الآخر قبل الانتهاء من أي شيء. ستساعد هذه الاستراتيجية على تعزيز الشعور بالأهمية والشمول لدى جميع الأطراف.',
      'Save':'يحفظ',
      'THANK YOU':'شكرًا لك',
      'your account has been successfully created':'تم إنشاء حسابك بنجاح',
      "CONTINUE":"يكمل",
      'Dashboard':'لوحة القيادة',
      'Menu':'قائمة طعام',
      'Promo Code List':'قائمة الرموز الترويجية',
      'Slot List':'قائمة الفتحات',
      'Total Earning':'مجموع الأرباح',
      'Set Store Time':'ضبط وقت المتجر',
      'Bank Details':'التفاصيل المصرفية',
      'Setting':'جلسة',
      'FeedBack':'تعليق',
      'Log Out':'تسجيل خروج',
      'Hi':'أهلاً',
      "Restaurant Time:":"وقت المطعم:",
      "Gross Sales":"إجمالي المبيعات",
      "Earning":"كسب",
      "Sold items":"العناصر المباعة",
      "Order Received":"طلب وارد",
      "Latest Sales":"أحدث المبيعات",
      "See All":"اظهار الكل",
      "Order No.":"رقم الطلب",
      "Status":"حالة",
      "Menu List":"قائمة القائمة",
      'Find for food...':'البحث عن الطعام...',
      "Delete Menu": "حذف القائمة",
      "Are you sure you want to delete this Menu":"هل أنت متأكد أنك تريد حذف هذه القائمة",
      "Cancel":"يلغي",
      "okay":"تمام",
      "No Menu Created":"لم يتم إنشاء قائمة",
      "Add Menu":"إضافة القائمة",
      "Dish Name":"اسم الطبق",
      'Please enter your menu name ':'الرجاء إدخال اسم القائمة الخاصة بك ',
      'Meat Pasta':'باستا لحم',
      "Price":"سعر",
      'Please enter price':'الرجاء إدخال السعر',
      "Discount":"تخفيض",
      "Menu Description":"وصف القائمة",
      'Please enter menu description ':'الرجاء إدخال وصف القائمة',
      "Upload images":"تحميل الصور",
      'Delivery':'توصيل',
      'Dining':'تناول الطعام',
      'Please select image':'الرجاء اختيار الصورة',
      'Please select booking type':'الرجاء تحديد نوع الحجز',
      'Select Picture from':'حدد صورة من',
      'Cropper':'كروبر',
      "Camera":"آلة تصوير",
      'Gallery':'صالة عرض',
      'Orders':'طلبات',
      'Wallet':'محفظة',
      'Order List':'لائحة الطلبات',
      "Your earning this month":"دخلك هذا الشهر",
      "Withdrawal":"انسحاب",
      "Filter":"منقي",
      "Yes":"نعم",
      "No":"لا",
      "False":"خطأ شنيع",
      "True":"حقيقي",
      "Search":"يبحث",
      "Dining Orders":"طلبات الطعام",
      "Delivery Orders":"أوامر التسليم",
      "No User Found":"لم يتم العثور على المستخدم",
      "Withdrawal Money":"سحب الأموال",
      "My Balance":"رصيدي",
      "Amount":"كمية",
      "Date":"تاريخ",
      "About Us":"معلومات عنا",
      'Please enter about yourself':'الرجاء الدخول عن نفسك',
      "Upload Restaurant Images or Videos":"قم بتحميل صور أو مقاطع فيديو للمطعم",
      "Upload Restaurant Menu Card":"تحميل بطاقة قائمة المطعم",
      'Image Gallery':'معرض الصور',
      'Choose From Gallery':'اختر من المعرض',
      "No Coupon Found":"لم يتم العثور على قسيمة",
      "Create promo code":"إنشاء رمز ترويجي",
      "Update promo code":"تحديث الرمز الترويجي",
      'Code is Updated':'تم تحديث الكود',
      'Code is Created':'تم إنشاء الكود',
      "Promo Code Name":"اسم الرمز الترويجي",
      'Please enter your Promo Code Name ':'الرجاء إدخال اسم الرمز الترويجي الخاص بك',
      'Sunday Code':'كود الأحد',
      'Code':'شفرة',
      'Happy sunday':'يوم احد سعيد',
      'Please enter your Code ':'الرجاء إدخال الرمز الخاص بك',
      'Please enter your Discount ':'الرجاء إدخال الخصم الخاص بك',
      "Max Discount":"ماكس الخصم",
      "Start Date":"تاريخ البدء",
      'Please enter start Date ':'الرجاء إدخال تاريخ البدء',
      'Select Start Date':'حدد تاريخ البدء',
      "End Date":"تاريخ الانتهاء",
      'Please enter end Date ':'الرجاء إدخال تاريخ الانتهاء',
      'Select End Date':'حدد تاريخ الانتهاء',
      'UPDATE COUPON':'تحديث القسيمة',
      'CREATE COUPON':'إنشاء قسيمة',
      'basad on 23 reviews':'بناءً على 23 تعليقًا',
      'Excellent        ':'ممتاز',
      'Good               ':'جيد',
      'Average          ':'متوسط',
      'Below Average':'أقل من المتوسط',
      "Set Delivery":"تعيين التسليم",
      "Cancellation":"إلغاء",
      "Menu selection":"اختيار القائمة",
      "Preparation time":"وقت التحضير",
      'Please enter your preparation Time':'الرجاء إدخال وقت التحضير الخاص بك',
      'Mint':'دقائق',
      "Average meal for 1 Member":"متوسط ​​الوجبة لعضو واحد",
      'Please enter your average Meal For 1 Member':'من فضلك قم بإدخال متوسط ​​الوجبة الخاصة بك لعضو واحد',
      'Submit':'يُقدِّم',
      "Please enter bank account Name":"الرجاء إدخال اسم الحساب البنكي",
      "Bank Account Number":"رقم الحساب المصرفي",
      "Please enter bank account number":"الرجاء إدخال رقم الحساب البنكي",
      "Account Holder Name":"اسم صاحب الحساب",
      "Please enter account holder name":"الرجاء إدخال اسم صاحب الحساب",
      "IFSC Code":"رمز إفسك",
      "Please enter IFSC code":"الرجاء إدخال رمز IFSC",
      "ADD ACCOUNT":"إضافة حساب",
      "Withdrawal Amount":"كمية السحب",
      "Order ID:":"طلب البطاقة التعريفية:",
      "Admin Commission":"اللجنة الادارية",
      "Slots are not created yet":"لم يتم إنشاء فتحات بعد",
      "Create Slot":"إنشاء فتحة",
      "Single Date":"تاريخ واحد",
      "Date Range":"نطاق الموعد",
      "Start date is required":"تاريخ البدء مطلوب",
      "End date is required":"تاريخ الانتهاء مطلوب",
      "Lunch Time Slot":"فتحة وقت الغداء",
      "Previous Slots":"الفتحات السابقة",
      "Create New":"خلق جديد إبداع جديد",
      "Dinner Time Slot":"فتحة وقت العشاء",
    }
  };}

