import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    //ENGLISH LANGUAGE
    'en_US': {

      'You first': 'You first',
      'We don’t charge you order fees. We don’t spy on you. We just help you enjoy your meals': 'We don’t charge you order fees. We don’t spy on you. We just help you enjoy your meals',
      'Beautifully-designed menus' : 'Beautifully-designed menus',
      'Every menu item is manually reviewed by our team' : 'Every menu item is manually reviewed by our team',
      "Unbeatable rates":"Unbeatable rates",
      'We don’t charge any order fees. Delivery fees go where they belong.':'We don’t charge any order fees. Delivery fees go where they belong.',
      'WELCOME':'WELCOME',
      'Login your account.':'Login your account.',
      "Login With Mobile Number":"Login With Mobile Number",
      "Login With Email Address":"Login With Email Address",
      'Enter Mobile Number': 'Enter Mobile Number',
      'Please enter phone number': 'Please enter phone number',
      'Phone Number not register yet Please Signup' : 'Phone Number not register yet Please Signup',
      "OTP has been sent": "OTP has been sent",
      "Oops, OTP send failed": "Oops, OTP send failed",
      'Email not register yet Please Signup': 'Email not register yet Please Signup',
      'Enter your Mobile number':'Enter your Mobile number',
      'Please enter your phone number':'Please enter your phone number',
      'Please enter your email':'Please enter your email',
      'Enter a valid email address':'Enter a valid email address',
      'Please enter your otp':'Please enter your otp',
      'Enter Email' : 'Enter Email',
      'send': 'send',
      'Enter Otp':'Enter Otp',
      "OTP is verified": "OTP is verified",
      "Invalid OTP" : "Invalid OTP",
      'Login' : 'Login',
      'Customer Booking?' : 'Customer Booking?',
      'Sign in as a business': 'Sign in as a business',
      'Or Login with' : 'Or Login with',
      'Facebook': 'Facebook',
      'Google': 'Google',
      "Don't Have an Account?": "Don't Have an Account?",
      'Signup' : 'Signup',
      'Email already exits':'Email already exits',
      'Mobile Number already exits': 'Mobile Number already exits',
      "Create Account": "Create Account",
      "Enter Your Name": "Enter Your Name",
      "Please enter your name": "Please enter your name",
      'Enter your Email':'Enter your Email',
      "Valid Email is required":"Valid Email is required",
      "Email is required":"Email is required",
      "Please accept term and conditions":"Please accept term and conditions",
      "Email":"Email",
      "Mobile Number":"Mobile Number",
      'Phone Number':'Phone Number',
      'Signup as a customer':'Signup as a customer',
      'Restaurant Registration': 'Restaurant Registration',
      'Please enter your Restaurant Name':'Please enter your Restaurant Name',
      "Category": "Category",
      "Select category" : "Select category",
      'Please select category' : 'Please select category',
      "No Category Available": "No Category Available",
"Address":"Address",
"Location":"Location",
'Accepted file types: JPEG, Doc, PDF, PNG':'Accepted file types: JPEG, Doc, PDF, PNG',
'Yes I understand and agree to the ':'Yes I understand and agree to the ',
'Terms And Conditions':'Terms And Conditions',
'Terms and conditions are part of a contract that ensure parties understand their contractual rights and obligations. Parties draft them into a legal contract, also called a legal agreement, in accordance with local, state, and federal contract laws. They set important boundaries that all contract principals must uphold.''Several contract types utilize terms and conditions. When there is a formal agreement to create with another individual or entity, consider how you would like to structure your deal and negotiate the terms and conditions with the other side before finalizing anything. This strategy will help foster a sense of importance and inclusion on all sides.':'Terms and conditions are part of a contract that ensure parties understand their contractual rights and obligations. Parties draft them into a legal contract, also called a legal agreement, in accordance with local, state, and federal contract laws. They set important boundaries that all contract principals must uphold.''Several contract types utilize terms and conditions. When there is a formal agreement to create with another individual or entity, consider how you would like to structure your deal and negotiate the terms and conditions with the other side before finalizing anything. This strategy will help foster a sense of importance and inclusion on all sides.',
'Save':'Save',
'THANK YOU':'THANK YOU',
'your account has been successfully created':'your account has been successfully created',
"CONTINUE":"CONTINUE",
'Dashboard':'Dashboard',
'Menu':'Menu',
'Promo Code List':'Promo Code List',
'Slot List':'Slot List',
'Total Earning':'Total Earning',
'Set Store Time':'Set Store Time',
'Bank Details':'Bank Details',
'Setting':'Setting',
'FeedBack':'FeedBack',
'Log Out':'Log Out',
'Hi':'Hi',
"Restaurant Time:":"Restaurant Time:",
"Gross Sales":"Gross Sales",
"Earning":"Earning",
"Sold items":"Sold items",
"Order Received":"Order Received",
"Latest Sales":"Latest Sales",
"See All":"See All",
"Order No.":"Order No.",
"Status":"Status",
"Menu List":"Menu List",
'Find for food...':'Find for food...',
"Delete Menu": "Delete Menu",
"Are you sure you want to delete this Menu":"Are you sure you want to delete this Menu",
"Cancel":"Cancel",
"okay":"okay",
"No Menu Created":"No Menu Created",
"Add Menu":"Add Menu",
"Dish Name":"Dish Name",
'Please enter your menu name ':'Please enter your menu name ',
'Meat Pasta':'Meat Pasta',
"Price":"Price",
'Please enter price':'Please enter price',
"Discount":"Discount",
"Menu Description":"Menu Description",
'Please enter menu description ':'Please enter menu description ',
"Upload images":"Upload images",
'Delivery':'Delivery',
'Dining':'Dining',
'Please select image':'Please select image',
'Please select booking type':'Please select booking type',
'Select Picture from':'Select Picture from',
'Cropper':'Cropper',
"Camera":"Camera",
'Gallery':'Gallery',
'Orders':'Orders',
'Wallet':'Wallet',
'Order List':'Order List',
"Your earning this month":"Your earning this month",
"Withdrawal":"Withdrawal",
"Filter":"Filter",
"Yes":"Yes",
"No":"No",
"False":"False",
"True":"True",
"Search":"Search",
"Dining Orders":"Dining Orders",
"Delivery Orders":"Delivery Orders",
"No User Found":"No User Found",
"Withdrawal Money":"Withdrawal Money",
"My Balance":"My Balance",
"Amount":"Amount",
"Date":"Date",
"About Us":"About Us",
'Please enter about yourself':'Please enter about yourself',
"Upload Restaurant Images or Videos":"Upload Restaurant Images or Videos",
"Upload Restaurant Menu Card":"Upload Restaurant Menu Card",
'Image Gallery':'Image Gallery',
'Choose From Gallery':'Choose From Gallery',
"No Coupon Found":"No Coupon Found",
"Create promo code":"Create promo code",
"Update promo code":"Update promo code",
'Code is Updated':'Code is Updated',
'Code is Created':'Code is Created',
"Promo Code Name":"Promo Code Name",
'Please enter your Promo Code Name ':'Please enter your Promo Code Name ',
'Sunday Code':'Sunday Code',
'Code':'Code',
'Happy sunday':'Happy sunday',
'Please enter your Code ':'Please enter your Code ',
'Please enter your Discount ':'Please enter your Discount ',
"Max Discount":"Max Discount",
"Start Date":"Start Date",
'Please enter start Date ':'Please enter start Date ',
'Select Start Date':'Select Start Date',
"End Date":"End Date",
'Please enter end Date ':'Please enter end Date ',
'Select End Date':'Select End Date',
'UPDATE COUPON':'UPDATE COUPON',
'CREATE COUPON':'CREATE COUPON',
'basad on 23 reviews':'basad on 23 reviews',
'Excellent        ':'Excellent        ',
'Good               ':'Good               ',
'Average          ':'Average          ',
'Below Average':'Below Average',
"Set Delivery":"Set Delivery",
"Cancellation":"Cancellation",
"Menu selection":"Menu selection",
"Preparation time":"Preparation time",
'Please enter your preparation Time':'Please enter your preparation Time',
'Mint':'Mint',
"Average meal for 1 Member":"Average meal for 1 Member",
'Please enter your average Meal For 1 Member':'Please enter your average Meal For 1 Member',
'Submit':'Submit',
"Please enter bank account Name":"Please enter bank account Name",
"Bank Account Number":"Bank Account Number",
"Please enter bank account number":"Please enter bank account number",
"Account Holder Name":"Account Holder Name",
"Please enter account holder name":"Please enter account holder name",
"IFSC Code":"IFSC Code",
"Please enter IFSC code":"Please enter IFSC code",
"ADD ACCOUNT":"ADD ACCOUNT",
"Withdrawal Amount":"Withdrawal Amount",
"Order ID:":"Order ID:",
"Admin Commission":"Admin Commission",
"Slots are not created yet":"Slots are not created yet",
"Create Slot":"Create Slot",
"Single Date":"Single Date",
"Date Range":"Date Range",
"Start date is required":"Start date is required",
"End date is required":"End date is required",
"Lunch Time Slot":"Lunch Time Slot",
"Previous Slots":"Previous Slots",
"Create New":"Create New",
"Dinner Time Slot":"Dinner Time Slot",



    }};}

